### ISSUE TITLE
How does one is supposed to control deluge without webui access?

### ISSUE THREAD

**Issue by EduMelo** [sgtsquiggs/docker-deluge-openvpn#1]
I was looking for a docker image like this, and I'm very glad to find this one.
But I don undestand how it could be useful without webui acces.

Could someone please help me to undestand this.

Thanks

**Comment by ghost** [comment]
Yeah that kind of eludes me as well. The readme is kind of unclear on this:

> Access the WebUI
>
> But what's going on? My http://my-host:8112 isn't responding? This is because the VPN is active, and since docker is running in a different ip range than your client the response to your request will be treated as "non-local" traffic and therefore be routed out through the VPN interface.

I'd expect the whitelisted local network to have access to the ui. Is that not the case with this image @sgtsquiggs? Because it doesn't seem to be the case with my testing.

For example, from a machine with the ip `192.168.1.9` I can't access the machine that this image is running on (`192.168.1.5`), even though I've set `192.168.1.0/24` as the local network and the container is logging the following:

```
Fri Feb 21 11:12:05 2020 [tunnel-up] Adding route to local network 192.168.1.0/24 via 192.168.1.1 dev eno1
```

**Comment by sgtsquiggs** [comment]
I haven't had any issues like this. I have this image running via docker-compose:

```yml
 deluge:
    image: sgtsquiggs/deluge-openvpn:v2
    container_name: deluge
    mem_limit: 4096m
    environment:
      - PUID=${WRITE_PUID}
      - PGID=${WRITE_PGID}
      - UMASK=0664
      - TZ=US/Eastern
      - "OPENVPN_PROVIDER=${VPN_PROVIDER}"
      - "OPENVPN_CONFIG=${VPN_CONFIG}"
      - "OPENVPN_USERNAME=${VPN_USERNAME}"
      - "OPENVPN_PASSWORD=${VPN_PASSWORD}"
      - "OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60"
      - "LOCAL_NETWORK=192.168.0.0/16"
    volumes:
      - (snipped)
    dns:
      - 1.1.1.1
      - 1.0.0.1
    ports:
      - 8112:8112
      - 58846:58846
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    networks:
      - backend
    restart: unless-stopped
```

`backend` in this example is a bridge network with several other images running.


I can access the WebUI from the machine docker is running on, as well as other machines on the same network.
