### ISSUE TITLE
Docker Compose support

### ISSUE THREAD

**Issue by Zelatrix** [sgtsquiggs/docker-deluge-openvpn#12]
I see on the Dockerhub page for this container that you create and start the container by using the `docker run` command. I can't see an option to start this using Compose, so I'm assuming that Compose isn't supported by this container. If this is the case, will it ever be supported, and if this is not the case and I can start the container using Compose, could you tell me how I can do so?

**Comment by Nouuu** [comment]
docker-compose is supported but you have to change the base docker-compose.yml file.
Here is the one i am using and it is working fine 👍 

```yml
version: '2'
services:
 deluge:
    image: sgtsquiggs/deluge-openvpn:v2
    container_name: deluge
    mem_limit: 1024m
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=0664
      - TZ=Europe/Paris
      - OPENVPN_PROVIDER=CUSTOM
      - OPENVPN_USERNAME=xxxxxx
      - OPENVPN_PASSWORD=xxxxxx
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
      - LOCAL_NETWORK=192.168.1.0/24
    volumes:
      - ../openvpn/openvpn.ovpn:/etc/openvpn/custom/default.ovpn
      - ../openvpn/client.crt:/etc/openvpn/custom/client.crt
      - ../openvpn/ca.crt:/etc/openvpn/custom/ca.crt
      - ../openvpn/client.key:/etc/openvpn/custom/client.key
      - ../openvpn/credentials.conf:/etc/openvpn/custom/credentials.conf
      - ../config:/config
      - ../../Torrents:/downloads
      - ../../Downloading:/downloading
      - /etc/localtime:/etc/localtime:ro
    dns:
      - 1.1.1.1
      - 1.0.0.1
    ports:
      - 8112:8112
      - 58846:58846
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    restart: unless-stopped
```

Check this issue, that might help you : https://github.com/sgtsquiggs/docker-deluge-openvpn/issues/5
