### ISSUE TITLE
CyberGhost custom provider: for sake of posterity

### ISSUE THREAD

**Issue by FunDeckHermit** [sgtsquiggs/docker-deluge-openvpn#5]
Hello,

I've been fiddling with a custom provider for quite some time now. The provider is called CyberGhost.
The key to fixing it was removing all relative paths inside the .ovpn file. 

My file structure looks like this:
/srv/docker/delugevpn/
---- openvpn/
-------- ca.crt    
-------- client.crt
-------- client.key
-------- credentials.conf
-------- openvpn.ovpn  
---- config/
---- docker-compose.yml

My docker-compose.yml looks like this:
```
version: '2'
services:
 deluge:
    image: sgtsquiggs/deluge-openvpn:v2
    container_name: deluge
    mem_limit: 4096m
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=0664
      - TZ=US/Eastern
      - OPENVPN_PROVIDER=CUSTOM
      - OPENVPN_USERNAME={username}
      - OPENVPN_PASSWORD={password}
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
      - LOCAL_NETWORK=192.168.178.0/24
    volumes:
      - ./openvpn/openvpn.ovpn:/etc/openvpn/custom/default.ovpn
      - ./openvpn/client.crt:/etc/openvpn/custom/client.crt
      - ./openvpn/ca.crt:/etc/openvpn/custom/ca.crt
      - ./openvpn/client.key:/etc/openvpn/custom/client.key
      - ./openvpn/credentials.conf:/etc/openvpn/custom/credentials.conf
      - ./config:/config
      - /mnt/king1/downloads:/downloads
      - /etc/localtime:/etc/localtime:ro
    dns:
      - 1.1.1.1
      - 1.0.0.1
    ports:
      - 8112:8112
      - 58846:58846
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    restart: unless-stopped
```
My ./openvpn/openvpn.ovpn file looks like this:
```
remote 87-1-pk.cg-dialup.net 443
client
dev tun
proto udp
auth-user-pass /etc/openvpn/custom/credentials.conf


resolv-retry infinite
redirect-gateway def1
persist-key
nobind
cipher AES-256-CBC
auth SHA256
ping 5
ping-exit 60
ping-timer-rem
explicit-exit-notify 2
script-security 2
remote-cert-tls server
route-delay 5
verb 4


ca /etc/openvpn/custom/ca.crt

cert /etc/openvpn/custom/client.crt

key /etc/openvpn/custom/client.key

```

You can close this issue immediately. This seems like the best place to share it.
