### ISSUE TITLE
Cannot connect to Sonarr using Docker compose

### ISSUE THREAD

**Issue by Jimbles** [sgtsquiggs/docker-deluge-openvpn#8]
Hey! Thanks again for setting up this container it was exactly what I needed :+1 

I am having some difficulty connecting Deluge to Sonarr/Radarr etc. using this container using `docker compose`. I have defined a network within the yml as below. Each service is available through my-host:8112 my-host:8989 etc. but Sonarr and Radarr cannot connect to Deluge when adding a download client using the default `host:localhost` `port:8112`. I appreciate this is probably more of a general Docker problem that specific to this container but any help you can offer would be great! 

```
version: "3.5"
services:
  delugevpn:
    env_file:
      - ../docker-deluge-openvpn/DockerEnv #vpn stuff in repo folder, other containers use .env
    image: delugevpn
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    restart: unless-stopped
    ports:
      - "8112:8112"
      - "58846:58846"
    networks:
      - backend
    dns:
      - 8.8.8.8
      - 8.8.4.4
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/pi/docker/deluge:/config
      - ${ROOT}:/media

  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr:latest
    restart: unless-stopped
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${ROOT}/config/sonarr:/config # config files
      - ${ROOT}/complete/tv:/tv # tv shows folder
      - ${ROOT}/downloads:/downloads # download folder
    ports:
      - 8989:8989
    networks:
      - backend

(Jackett Radarr and Bazarr clipped)

networks:
  backend:
    driver: bridge
```
